#ifndef __LIBEMBER_UTIL_INLINE_HPP
#define __LIBEMBER_UTIL_INLINE_HPP

#ifdef LIBEMBER_HEADER_ONLY
#  define LIBEMBER_INLINE inline
#  define LIBEMBER_EXTERN
#else
#  define LIBEMBER_INLINE
#  define LIBEMBER_EXTERN extern
#endif

#endif  // __LIBEMBER_UTIL_INLINE_HPP

